# **Trump Tariff DataSet Analysis:**

**Source:** __https://www.kaggle.com/datasets/mesumraza/trump-tarrif-data__

In [2]:
import pandas as pd 
pd.read_excel("C:/Users/MyMachine/Desktop/Mission-Project/00_DataSets/20_Trump_Tariff_Data_1.xlsx")

,Country,US 2024 Deficit,US 2024 Exports,US 2024 Imports (Customs Basis),Trump Tariffs Alleged,Trump Response,Population
0,Afghanistan,-11.1,11.4,22.6,0.49,0.25,41454761.0
1,Albania,13.4,141.7,128.3,0.10,0.10,2745972.0
2,Algeria,-1447.1,1014.5,2461.6,0.59,0.29,46164219.0
3,Andorra,1.5,4.9,3.4,0.10,0.10,80856.0
4,Angola,-1186.9,682.4,1869.2,0.63,0.32,36749906.0
...,...,...,...,...,...,...,...
199,Vietnam,-123463.0,13098.2,136561.2,0.90,0.45,100352192.0
200,West Bank Administered by Israel,-2.3,3.7,6.0,0.38,0.19,NaN
201,Yemen,125.2,134.1,8.9,0.10,0.10,39390799.0
202,Zambia,-55.3,113.8,169.1,0.33,0.16,20723965.0
203,Zimbabwe,-24.1,43.8,67.8,0.36,0.18,16340822.0